---
- name: Check if user is absent
  win_domain_user:
    name: "{{ user_login }}"
    state: query
  register: user_exists
  
- block:  
  - name: fail
    fail:
      msg: "Usúario já existe no AD!"
  when: user_exists.state == "present"

- block:
  - name: Generate complex password
    set_fact:
      genpass_user: "{{ lookup('password', '/dev/null length=15 chars=ascii_lowercase,ascii_uppercase,digits,punctuation') }}"
  - block:
    - name: Create user
      win_domain_user:
        name: "{{ user_login }}"
        firstname: "{{ user_firstname }}"
        surname: "{{ user_lastname }}"
        password: "{{ genpass_user }}"
        password_never_expires: no
        update_password: on_create
        user_cannot_change_password: no
        password_expired: yes
        enabled: yes
        account_locked: no
        # path: "{{ user_ou }}"
        state: present
      register: user_create
    when: action == "createUser"

  - block:
    - name: Create Service User
      win_domain_user:
        name: "{{ user_login }}"
        password: "{{ genpass_user }}"
        description: "{{ description }}"
        password_never_expires: yes
        update_password: on_create
        user_cannot_change_password: yes
        enabled: yes
        account_locked: no
        # path: "{{ user_ou }}"
        state: present
      register: user_create
    when: action == "createSVCUser"

  - name: Usuario criado com sucesso
    debug:
      msg: "Usuário criado com sucesso!"
    when: user_create.state == 'present'
  
  when: user_exists.state == "absent"