---
- name: Check if user is absent
  win_domain_user:
    name: "{{ user }}"
    state: query
  register: user_exists
  
- block:  
  - name: fail
    fail:
      msg: "Usúario já existe no AD!"
  when: user_exists.state == "present"

- block:
  - name: Generate complex password
    set_fact:
      genpass: "{{ lookup('password', '/dev/null length=15 chars=ascii_lowercase,ascii_uppercase,digits,punctuation') }}"
  
  - block:
    - name: Create user
      win_domain_user:
        name: "{{ user }}"
        upn: "{{ user }}@{{ domain }}"
        firstname: "{{ user_firstname }}"
        surname: "{{ user_lastname }}"
        password: "{{ genpass}}"
        update_password: on_create
        user_cannot_change_password: no
        password_expired: yes
        enabled: yes
        account_locked: no
        # path: "{{ user_ou }}"
        state: present
      register: user_create

    - name: User created successful
      debug:
        msg: 
        - "Usuário criado com sucesso!"
        - "{{ user }}"
        - "{{ genpass }}"
      when: user_create.state == 'present'

    when: action == "createUser"

  - block:
    - name: Create Service User
      win_domain_user:
        name: "{{ user }}"
        upn: " {{ user }}@{{ domain }} "
        password: "{{ genpass }}"
        description: "{{ description }}"
        password_never_expires: yes
        update_password: on_create
        user_cannot_change_password: yes
        enabled: yes
        account_locked: no
        # path: "{{ user_ou }}"
        state: present
      register: user_create

    - name: User created successful
      debug:
        msg: 
        - "Usuário criado com sucesso!"
        - "{{ user }}"
        - "{{ genpass }}"
      when: user_create.state == 'present'

    when: action == "createSVCUser"
  
  when: user_exists.state == "absent"